const express = require('express')
const app = express()
const cors = require('cors')
const bodyParser = require('body-parser')
const methodOverride = require('method-override')
const itemRoutes = require('./routes/item')
const userRoutes = require('./routes/user')

app.use(cors())
app.use(methodOverride('_method'))
app.use(bodyParser.json())
app.use(userRoutes)
app.use(itemRoutes)

app.set('port', process.env.PORT || 8081)
app.listen(process.env.PORT || 8081, () => console.log('listen on port 8081'))
